Написать автотесты на следующую функциональность: Создание проекта и Создание build config
AlexKrosb/Teamcity-Test pull request #1
Opened 2023-12-05 08:06 UTC by AlexKrosb

Дописал в RolesTest тесты для Project developer, Project viewer и Agent manager проверку на создание проекта в двух скоупах.

В классе CreateProjectTest написал тесты на проверку валидации полей класса parentProject -> locator, name и id ( везде где смог подписал комментариями )

В классе BuildConfigurationTest написал тесты на проверку валидации полей для id (buildTypeId), name и id ( projectId ). 

Везде где нашел баг подписал комментарием. 

Не успел реализовать очистку данных для тех тестов, где данные не генерировались через генератор данных, а описывались через билдер.

2023-12-08 21:49 UTC, AlexPshe requested changes
Привет!

Большое спасибо за качественное выполнение задания!

Я добавила несколько комментов по улучшению - нужно пофиксить их за неделю и будет зачтено ⚡️

2023-12-08 21:49 UTC, AlexPshe commented on src/main/java/com/example/teamcity/api/requests/checked/CheckedProject.java
> +    public Project createCheckedProjectWithParameter(String name, String locator, String id ) {
Хммм, а зачем нам этот метод, если у нас есть обычный `create`?

Тут ты в одном методе объединяешь 2 функциональности - генерация проекта и создание сущности, что не очень хорошо, ты можешь отдельно генерировать проект, как мы уже делали в testData, а потом с помощьб set методов переопределять поле name, locator, id. 

Если эта часть не получится - давай созвонимся и я обьясню)

2023-12-08 21:49 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +    public Object[][] buildConfigIdTestCorrectSymbols() {
Огонь!

2023-12-08 21:49 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/BuildConfigurationTest.java
> +//Check that Build configuration with name already exists in project
Тут бы выровнять код :) 
`Ctrl + A`
потом в меню IDE 
`Code` -> `Reformat Code`

2023-12-08 21:49 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/RolesTest.java
> +    ALERT _ _ _ _ _ BUG!BUG!BUG!BUG!BUG!BUG! Expected status code <403> but was <200>.
Хах, это верно!

2023-12-13 19:53 UTC, AlexKrosb commented
Добавил второй коммит в ту же ветку. 
Я бы очень хотел, чтобы та часть не получилось и мы бы созвонились, но я понял, что ты имела ввиду, переделал через сеттер, получается testdata остается и автоматом подчищается, не пришлось реализовывать очистку данных для тех тестов, где данные не генерировались через генератор данных. Ну, и выровнил код.

2023-12-17 14:23 UTC, AlexPshe approved these changes
Отлично, все зачтено!

2023-12-17 18:10 UTC, merged