UI test - Домашнее задание 2
AlexKrosb/Teamcity-Test pull request #3
Opened 2023-12-18 07:21 UTC by AlexKrosb

Привет!
Сделал все в едином классе, не стал делать для проекта и конфига. Надеюсь, по поводу проверок апи я правильно, понял, честно не уверен в этом решении. Так же во втором методе написал все проверки на errorname в случае когда невалидные данные, как понял мы же проверяем только то, что не удается проверить в апи, а это текстовки. Я помню из видео, что мы можешь поделить на 2 класса создание проекта manually и url, я создавал отдельно класс Manuall с extends CreateNewProject, но так как в методах по типу open наш возвращаемый объект все еще рассматривается как объект типа CreateNewProject, я не придумал как обойти это и просто добавил как новый метод createProjectManually в класс CreateNewProject.

2023-12-29 12:50 UTC, AlexPshe requested changes
Привет! 

Спасибо за выполненное ДЗ, все гуд, но нужно пофиксить комменты до 10 января и зачтем за сданное 🔥

С наступающим! 🎄

2023-12-29 12:50 UTC, AlexPshe commented on src/main/java/com/example/teamcity/ui/pages/admin/CreateNewProject.java
> +        if (url.isEmpty()) {
Так-так, это все-таки два разных теста, можно параметризоровать тест по двум параметрам - url и текст ошибки, тогда можно будет в рамках одного кода, но двумя разными тестами с помощью DataProvider организовать.

2023-12-29 12:50 UTC, AlexPshe commented on src/main/java/com/example/teamcity/ui/pages/admin/CreateNewProject.java
> +        if (url.isEmpty()) {
И также проверка ошибок внутри PageObject - плохая практика, так как неочевидно для вызывающих метод, что ты под капотом будешь проверять. Необходимо вытащить эту логику в сам тест.

2023-12-29 12:50 UTC, AlexPshe commented on src/test/java/com/example/teamcity/ui/CreateNewProjectTest.java
> +        var project = checkedWithSuperUser.getProjectRequest().get(testData.getProject().getId());
А как ты узнал project id, если ты проект через UI создаешь? 
То, что в testData сгенерировано не попадет внутрь API ведь при создании сущности через UI. Там какой-то рандомный id по логике должен быть?

2024-01-09 12:03 UTC, AlexKrosb commented
Привет, с наступившим !
Исправил по твоим комментариям все замечания. 
Исправил проверка на API уровне полей проекта и билда через запросы CheckedListProjects и CheckedListBuildConfigurationOfProject и фильтра. 

Разделил тесты по параметризации, а так же отдельно выделил создание проекта мануально, для этого создал класс  CreateNewProjectManually, как говорила ты в видео. В негативных кейсах отдельно выделил проверку текстовки ошибок в класс CheckErrorsOnPages - наверное надо было конкретно под создания проекта и билда завести класс, но решил общий сделать, мог бы сразу в тестах написать, но грамоздка получилось бы. Тесты почти 10 из 10, редко authorizedUserShouldBeAbleCreateNewProjectManually падает, но так и не смог дофиксить.

2024-01-21 13:54 UTC, AlexPshe approved these changes
Намного лучше! 🔥

2024-02-11 12:16 UTC, merged