Hometask 3
AlexKrosb/Teamcity-Test pull request #6
Opened 2024-02-13 19:34 UTC by AlexKrosb

2024-02-13 19:38 UTC, AlexKrosb commented
Комментарии куда-то делись, создал пул-реквест на другую ветку, чтобы было видно все изменения для дз3 в пул реквесте. Смог наконец-то поправить ошибку в тестах, падало из-за startUpTest и setupTeamCityAgentTest.

2024-02-13 20:37 UTC, AlexPshe requested changes
Привет! 

По скрипту все отлично, но нужно поправить авторизацию агента ⚡️

2024-02-15 12:48 UTC, AlexPshe requested changes
Привет! 

По скрипту все ок, но агента нужно авторизовывать через API - всегда спускаемся на самый низкий возможный уровень. 

Давай доделаем и будет зачтено ⚡️

2024-02-15 12:48 UTC, AlexPshe commented on src/test/java/com/example/teamcity/ui/SetupTest.java
> +        new AgentAuthPage()
Все огонь, но почему авторизация агента через UI?

2024-02-23 16:39 UTC, AlexKrosb commented
src/test/java/com/example/teamcity/api/AgentsAuthorizedTest.java

Добавил Api авторизацию, поменял пути запуска теста.

2024-02-23 16:40 UTC, AlexKrosb commented on src/test/java/com/example/teamcity/ui/SetupTest.java
> +        new AgentAuthPage()
Добавил Api авторизацию, поменял пути запуска теста.

2024-02-24 08:34 UTC, AlexKrosb commented on src/test/java/com/example/teamcity/ui/SetupTest.java
> +        new AgentAuthPage()
Поменял чутка yaml файл для 4 дз, можно смотреть последний коммит.

2024-02-25 09:57 UTC, AlexPshe approved these changes

2024-02-25 11:17 UTC, merged